version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["./wait-for-postgres.sh", "postgres:5432", "--", "python", "main.py"]
    ports:
      - 8000:8000
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - main-network
    volumes:
      - .:/code
    depends_on:
      - postgres
    restart: always
    
  postgres:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - main-network
    env_file:
      - .env
    restart: always
  
volumes:
  db:
    driver: local
    
networks:
  main-network:
